title: Michael's Blog
author: Michael B
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  An exciting blog about my journey in the software development space, from graduate developer to where ever the future takes me.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  michaelbish # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
